# typed: false
# frozen_string_literal: true

# Auto-generated by ax-code release tooling — do not edit manually.
#
# node-bundled formula for ax-code. The macOS asset is a node-bundled
# distribution (bin + lib + node_modules), not a single compiled binary, so the
# whole tree installs into libexec and bin/ax-code is a wrapper that runs the
# bundle with the Homebrew node (the launcher needs --experimental-ffi for
# OpenTUI's node:ffi backend and suppresses Node's experimental FFI notice).
class AxCode < Formula
  desc "Sovereign AI coding agent — provider-agnostic, LSP-first"
  homepage "https://github.com/defai-digital/ax-code"
  url "https://github.com/defai-digital/ax-code/releases/download/v7.5.0/ax-code-darwin-arm64.zip"
  version "7.5.0"
  sha256 "52d856eb05ee8ce5887c61f55cb795daba7f3a045ac7cc5e0a0ef82d1102128c"
  license "Apache-2.0"

  depends_on arch: :arm64
  depends_on :macos
  depends_on "node"
  depends_on "ripgrep"

  # The vendored OpenTUI native library is a prebuilt Mach-O with an @rpath
  # install id and zero Mach-O header padding. Homebrew's post-install
  # fix_dynamic_linkage tries to rewrite its dylib id to the long Cellar/opt path
  # and fails ("Updated load commands do not fit in the header"), making the
  # install exit non-zero even though the keg is fine. node:ffi dlopens the
  # library by absolute path at runtime, so its install id is irrelevant. Gzip it
  # during install so the Mach-O linkage scan skips it, then restore it in
  # post_install, which runs after fix_dynamic_linkage.
  OPENTUI_DYLIB = "node_modules/@opentui/core-darwin-arm64/libopentui.dylib"

  def install
    libexec.install Dir["*"]
    (bin/"ax-code").write <<~SH
      #!/bin/sh
      exec "#{formula_opt_bin("node")}/node" --experimental-ffi --disable-warning=ExperimentalWarning "#{libexec}/lib/index-node-tui.js" "$@"
    SH
    chmod 0755, bin/"ax-code"

    dylib = libexec/OPENTUI_DYLIB
    system "gzip", "-n", "--", dylib if dylib.exist?
  end

  def post_install
    gz = libexec/"#{OPENTUI_DYLIB}.gz"
    return unless gz.exist?

    chmod 0755, gz.dirname
    system "gunzip", "--", gz
  end

  # Homebrew refuses to link any formula while an installed cask shares its
  # token, and upgrade cleanup then removes the previously linked keg — the
  # ax-code command silently vanishes from PATH. The Desktop cask now ships as
  # "ax-code-desktop", but installs of its short-lived "ax-code" token still
  # trigger the skip; give those users the exact recovery commands.
  def caveats
    return unless (HOMEBREW_PREFIX/"Caskroom/ax-code").directory?

    <<~EOS
      The deprecated "ax-code" Desktop cask is installed, so Homebrew skips
      linking this formula and the ax-code command may be missing from PATH.

      Restore the CLI with:
        brew link ax-code
        hash -r

      Then move the Desktop app to its renamed cask:
        brew upgrade --cask ax-code
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ax-code --version")
  end
end
